### ISSUE TITLE
Exception in defer callback: Error: When the modifier option is true, validation object must have at least one operator

### ISSUE THREAD

**Issue by almogdesign** [TelescopeJS/Telescope#1081]
I'm trying to add the roles package and then set a custom user role like guest or member so I can use it with paid plans. I'm getting the following error 
```
Exception in defer callback: Error: When the modifier option is true, validation object must have at least one operator
at checkModifier (packages/aldeed:simple-schema/simple-schema-validation.js:271:1)
at doValidation1 (packages/aldeed:simple-schema/simple-schema-validation.js:321:1)
```

When I run the following function 
```javascript
Meteor.methods({
    setUserRole: function(userId, roleToSet){
        // check(Meteor.userId(), String);
        check(userId, String );
        check(roleToSet, String);

        var user = Meteor.users.findOne(userId);

        if (_.isEmpty(user.roles)) {
            Roles.addUsersToRoles(userId, roleToSet);
        }
    }
});
```

**Comment by SachaG** [comment]
This is more of a support request than an issue with Telescope, so I don't think it fits in with the other issues. I'll close it for now.
