### ISSUE TITLE
Getting-started tutorial does not run

### ISSUE THREAD

**Issue by eric-burel** [telescopejs/telescope#11]
Hi, on a fresh install this morning, on the `getting-started` branch:

```
=> App running at: http://localhost:3000/
I20180309-09:46:29.483(1)? url:  /
I20180309-09:46:29.484(1)? { TypeError: Cannot read property '_id' of null
I20180309-09:46:29.485(1)?     at TextBlocks.React.createElement.textArray.map (packages/getting-started/lib/components/steps/Step.jsx:36:60)
I20180309-09:46:29.485(1)?     at Array.map (<anonymous>)
I20180309-09:46:29.485(1)?     at TextBlocks (packages/getting-started/lib/components/steps/Step.jsx:23:16)
I20180309-09:46:29.485(1)?     at walkTree (/home/eric-burel/Websites/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:716:21)
I20180309-09:46:29.486(1)?     at /home/eric-burel/Websites/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:729:21
I20180309-09:46:29.486(1)?     at forEachSingleChild (/home/eric-burel/Websites/Vulcan-Starter/node_modules/react/cjs/react.development.js:858:8)
I20180309-09:46:29.486(1)?     at traverseAllChildrenImpl (/home/eric-burel/Websites/Vulcan-Starter/node_modules/react/cjs/react.development.js:762:5)
I20180309-09:46:29.486(1)?     at traverseAllChildrenImpl (/home/eric-burel/Websites/Vulcan-Starter/node_modules/react/cjs/react.development.js:778:23)
I20180309-09:46:29.486(1)?     at traverseAllChildren (/home/eric-burel/Websites/Vulcan-Starter/node_modules/react/cjs/react.development.js:833:10)
I20180309-09:46:29.486(1)?     at Object.forEachChildren [as forEach] (/home/eric-burel/Websites/Vulcan-Starter/node_modules/react/cjs/react.development.js:878:3)
I20180309-09:46:29.487(1)?  => awaited here:
I20180309-09:46:29.487(1)?     at Function.Promise.await (/home/eric-burel/.meteor/packages/promise/.0.10.2.1tr237d.jazx++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20180309-09:46:29.487(1)?     at Object.preRender (packages/vulcan:routing/lib/server/routing.jsx:57:14)
I20180309-09:46:29.487(1)?     at generateSSRData (packages/vulcan:routing/lib/server/router.jsx:53:15)
I20180309-09:46:29.487(1)?     at sendSSRHtml (packages/vulcan:routing/lib/server/router.jsx:87:45)
I20180309-09:46:29.487(1)?     at match (packages/vulcan:routing/lib/server/router.jsx:150:11)
I20180309-09:46:29.487(1)?     at /home/eric-burel/Websites/Vulcan-Starter/node_modules/react-router/lib/match.js:67:5
I20180309-09:46:29.488(1)?     at /home/eric-burel/Websites/Vulcan-Starter/node_modules/react-router/lib/createTransitionManager.js:108:11
I20180309-09:46:29.488(1)?     at done (/home/eric-burel/Websites/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:79:19)
I20180309-09:46:29.488(1)?     at /home/eric-burel/Websites/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:85:7
I20180309-09:46:29.488(1)?     at getComponentsForRoute (/home/eric-burel/Websites/Vulcan-Starter/node_modules/react-router/lib/getComponents.js:11:5) queryErrors: [ [Circular] ] }
```
I suspect an incorrectly seeded database ?

**Comment by imcuttle** [comment]
Hi, @eric-burel !
Sorry, I guess the repo is not you wanted #10 .

**Comment by eric-burel** [comment]
Absolutely sorry @imcuttle  I messed up, I don't even use the Meteor Telescope app but its new version Vulcan ^^ Thanks for signaling the issue
