### ISSUE TITLE
Can't send newsletter w/ mupx setup (spiderable PhantomJS error)

### ISSUE THREAD

**Issue by williammwhite** [TelescopeJS/Telescope#1116]
I used mupx to setup and deploy and everything was working great until the newsletter was scheduled to be sent out.  The posts get tagged as sent but no connection is made to Mailchimp to create a new campaign.   

When I trigger manually using the 'testCampaign' call in the browser it works fine:

// Creating campaign…
// Campaign created
// Campaign scheduled for 2015-09-02 20:21:42

But when it gets triggered automatically (based on the time the newsletter is supposed to go out) I get:

spiderable: phantomjs failed: Error: Command failed: Can't open '/dev/stdin'
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5) 
stderr: Can't open '/dev/stdin'
[104.130.132.53]     at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
    at next (/bundle/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at Object.Package [as handle] (packages/cfs:http-methods/http.methods.server.api.js:418:1)
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
    at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
    at next (/bundle/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at Object.Package [as handle] (packages/cfs:http-methods/http.methods.server.api.js:418:1)
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.

I saw someone else had this issue and uninstalled phtantomJS via npm and added ongoworks:spiderable, but since everything is deployed into the docker container - how do I do this? 

Thanks,

WW

**Comment by williammwhite** [comment]
So I tried: 

meteor add ongoworks:spiderable 

and redeployed.  Now the error message has disappeared from the log but the Mailchimp campaign is still not getting generated.  In the log I just see a datetime stamp 1 hour before the newsletter is scheduled to be pushed.  Nothing else.

Any ideas?  Works fine when I trigger manually.  Deployed to Ubuntu 15.04 instance on Rackspace.

Thanks,
 
WW

**Comment by williammwhite** [comment]
OK.  This is working now. 

meteor add ongoworks:spiderable solved the problem. 

I was confused by a lagging cron job with my second comment.  All is well.  (-:

**Comment by frabrunelle** [comment]
Hum... I'm having the same issue. I added 'ongoworks:spiderable', but I keep getting the same error. I'm running Ubuntu 14.04 on DigitalOcean and deploying with mupx (I found it was easier to add an SSL certificate with mupx).

```
[45.55.84.118] spiderable: phantomjs failed: { [Error: Command failed: Can't open '/dev/stdin'
] killed: false, code: 255, signal: null }
stderr: Can't open '/dev/stdin'

[45.55.84.118] spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' }
stderr:
[45.55.84.118] Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
    at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
    at next (/bundle/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at packages/ongoworks:spiderable/spiderable_server.js:131:1
```
