### ISSUE TITLE
Exception while invoking method 'increasePostViews'

### ISSUE THREAD

**Issue by AdhamDannaway** [TelescopeJS/Telescope#1160]
Hi Guys,

I've grabbed the latest version of the sample project I'm seeing the following error reported in the logs:

Exception while invoking method 'increasePostViews' Error: Match error: Expected string, got object
    at checkSubtree (packages/check/match.js:159:1)
    at check (packages/check/match.js:32:1)
    at [object Object].Meteor.methods.increasePostViews (packages/telescope:posts/lib/methods.js:283:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)

Anyone else experiencing the same issue? if so do you have a workaround?

**Comment by xavcz** [comment]
Hey, @AdhamDannaway! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
