### ISSUE TITLE
Can't sign in as admin & can't edit post

### ISSUE THREAD

**Issue by atseng3** [TelescopeJS/Telescope#1166]
So I have 2 issues:
1. After I selected to "only" login as with Twitter as the admin, I was forced to log out and then I had to log in with my Twitter account, this effectively makes me a "non-admin" and therefore I cannot log in as an admin again...seems like ever. I need to log in so I can approve some posts!

This is a separate issue from the one above.
2. I haven't been able to edit my posts at all, whenever I try I just get an internal server error and that's it. Please Help!! 

But overall I'm definitely loving the app and would recommend to anyone else trying to build something similar. 

please email me for a link to my site, my email is atseng3@gmail.com

**Comment by SachaG** [comment]
Yeah, this is not great right now. You'll have to create a new Twitter-based account, log out, then log back in with your first admin account (you can do so by unhiding the email/password fields using the browser inspector, they're just set to `display:none`) and then making your new account admin as well.

**Comment by amelialin** [comment]
Having the same problem with editing posts; whenever I try to edit an already-existing post, as an admin, it gives me an internal server error. Were you able to find a solution to this?

**Comment by SachaG** [comment]
@amelialin what's the content of the internal server error (look in your server logs)?

**Comment by amelialin** [comment]
I think this is the relevant bit. Let me know if you need more!

```
2015-10-29T20:49:02.848369+00:00 app[web.1]: Exception while invoking method 'editPost' MongoError: Cannot update 'categories' and 'categories' at the same time
2015-10-29T20:49:02.848373+00:00 app[web.1]:     at Object.Future.wait (/app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:398:15)
2015-10-29T20:49:02.848374+00:00 app[web.1]:     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
2015-10-29T20:49:02.848375+00:00 app[web.1]:     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)
2015-10-29T20:49:02.848375+00:00 app[web.1]:     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/packages/matb33_collection-hooks.js:457:1)
2015-10-29T20:49:02.848377+00:00 app[web.1]:     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/packages/matb33_collection-hooks.js:125:1)
2015-10-29T20:49:02.848378+00:00 app[web.1]:     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:586:1)
2015-10-29T20:49:02.848378+00:00 app[web.1]:     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2/packages/aldeed_collection2.js:195:1)
2015-10-29T20:49:02.848379+00:00 app[web.1]:     at [object Object].Posts.edit (lib/methods.js:93:9)
2015-10-29T20:49:02.848380+00:00 app[web.1]:     at [object Object].Meteor.methods.editPost (lib/methods.js:227:18)
2015-10-29T20:49:02.848419+00:00 app[web.1]:     at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2554:1)
2015-10-29T20:49:02.848420+00:00 app[web.1]:     - - - - -
2015-10-29T20:49:02.848420+00:00 app[web.1]:     at Object.toError (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
2015-10-29T20:49:02.848421+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
2015-10-29T20:49:02.848421+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7
2015-10-29T20:49:02.848422+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
2015-10-29T20:49:02.848423+00:00 app[web.1]:     at Server.Base._callHandler (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
2015-10-29T20:49:02.848423+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
2015-10-29T20:49:02.848424+00:00 app[web.1]:     at [object Object].MongoReply.parseBody (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
2015-10-29T20:49:02.848425+00:00 app[web.1]:     at [object Object].<anonymous> (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
2015-10-29T20:49:02.848426+00:00 app[web.1]:     at [object Object].emit (events.js:95:17)
2015-10-29T20:49:02.848426+00:00 app[web.1]:     at [object Object].<anonymous> (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

**Comment by SachaG** [comment]
So I think this was fixed in recent versions. I think this is something that was happening when you try to edit a post without any categories created in your app. Can you update and let me know if it works?

**Comment by amelialin** [comment]
Ah, thank you! You are correct, I do not currently have any categories
created. I will update--I'd been putting it off for a few days. Appreciate
the help, Sacha! I will let you know if I continue to experience problems.

Amelia

On Thursday, October 29, 2015, Sacha Greif <notifications@github.com> wrote:

> So I think this was fixed in recent versions. I think this is something
> that was happening when you try to edit a post without any categories
> created in your app. Can you update and let me know if it works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TelescopeJS/Telescope/issues/1166#issuecomment-152368118>
> .
>


-- 
Sent from Gmail Mobile

**Comment by xavcz** [comment]
Hey, @amelialin! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
