### ISSUE TITLE
Exception while invoking method 'increasePostViews' MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}

### ISSUE THREAD

**Issue by sneakertack** [TelescopeJS/Telescope#1182]
As of Mongo 2.6 an update parameter can no longer have a `$set` operator that points to an empty no-op object, e.g. `Posts.update({_id: 'someid'}, {$set: {}, $inc: {viewCount: 1}})` will now fail.

[This line](https://github.com/TelescopeJS/Telescope/blob/1047f9b91f1ac9e483f14699a7e0669c893141c8/packages/telescope-posts/lib/methods.js#L298) seems to be the one that starts the error. Although it doesn't set `$set`, 1 of the Meteor collection libraries is probably auto-setting it.

The proper way to resolve this would probably be to figure out whether its collection2 or collection-hooks or simple-schema or something similar that's erroneously setting the empty $set object, then submitting an appropriate pull request upstream.

However there is also a quick, hacky solution, which would be to amend the line to the following:

`Posts.update(postId, { $set: {_id: postId}, $inc: { viewCount: 1 }});`

This way, it fulfills the non-empty criteria with a redundant write. Might be good as a stop-gap fix.

*Stack Trace:*

```
Exception while invoking method 'increasePostViews' MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at Object.Future.wait (/root/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:736:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)
    at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2/packages/aldeed_collection2.js:195:1)
    at [object Object].Meteor.methods.increasePostViews (lib/methods.js:298:13)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    - - - - -
    at Object.toError (/root/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /root/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
    at /root/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7
    at /root/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/root/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /root/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/root/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/root/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/root/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

**Comment by ghaliano** [comment]
@sneakertack  are you using SimpleSchema too ?

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
