### ISSUE TITLE
Updated to Meteor 1.2.1 Error!

### ISSUE THREAD

**Issue by meteorplus** [TelescopeJS/Telescope#1185]
Error: deny: Value for `update` must be a function

Hi
I got this error when I updated to Meteor 1.2.1.            
                                              
```
Changes to your project's package version selections from updating package versions:
                                              
cosmos:browserify           upgraded from 0.8.0 to 0.8.1
dburles:collection-helpers  upgraded from 1.0.3 to 1.0.4
meteorhacks:inject-initial  upgraded from 1.0.2 to 1.0.3
utilities:menu              upgraded from 0.1.5 to 0.1.6
                                              
Newer versions of the following indirect dependencies are available:
 * djedi:sanitize-html 1.10.1 (1.11.1 is available)
 * fourseven:scss 3.3.3_3 (3.4.1 is available)
 * kadira:blaze-layout 2.1.0 (2.2.0 is available)
 * kadira:dochead 1.2.2 (1.3.2 is available)  
 * meteorhacks:kadira 2.23.6 (2.25.0 is available)
To update one or more of these packages, pass their names to `meteor update`.

=> Started proxy.                             
=> Started MongoDB.                           
W20151030-19:56:15.405(-4)? (STDERR)          
W20151030-19:56:15.406(-4)? (STDERR) /root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151030-19:56:15.407(-4)? (STDERR)                                            throw(ex);
W20151030-19:56:15.407(-4)? (STDERR)                                                  ^
W20151030-19:56:15.407(-4)? (STDERR) Error: deny: Value for `update` must be a function
W20151030-19:56:15.407(-4)? (STDERR)     at packages/mongo/collection.js:755:1
W20151030-19:56:15.407(-4)? (STDERR)     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
W20151030-19:56:15.407(-4)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20151030-19:56:15.408(-4)? (STDERR)     at [object Object].addValidator (packages/mongo/collection.js:752:1)
W20151030-19:56:15.408(-4)? (STDERR)     at [object Object].Mongo.Collection.deny (packages/mongo/collection.js:804:1)
W20151030-19:56:15.408(-4)? (STDERR)     at Posts.getNotificationProperties.properties.postAuthorName (lib/herald.js:7:21)
W20151030-19:56:15.408(-4)? (STDERR)     at /root/workspace/pTelescope/xartfull/.meteor/local/build/programs/server/boot.js:249:5
=> Exited with code: 8
W20151030-19:56:28.102(-4)? (STDERR)          
W20151030-19:56:28.104(-4)? (STDERR) /root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151030-19:56:28.105(-4)? (STDERR)                                            throw(ex);
W20151030-19:56:28.105(-4)? (STDERR)                                                  ^
W20151030-19:56:28.230(-4)? (STDERR) Error: deny: Value for `update` must be a function
W20151030-19:56:28.230(-4)? (STDERR)     at packages/mongo/collection.js:755:1
W20151030-19:56:28.231(-4)? (STDERR)     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
W20151030-19:56:28.231(-4)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20151030-19:56:28.231(-4)? (STDERR)     at [object Object].addValidator (packages/mongo/collection.js:752:1)
W20151030-19:56:28.231(-4)? (STDERR)     at [object Object].Mongo.Collection.deny (packages/mongo/collection.js:804:1)
W20151030-19:56:28.231(-4)? (STDERR)     at Posts.getNotificationProperties.properties.postAuthorName (lib/herald.js:7:21)
W20151030-19:56:28.231(-4)? (STDERR)     at /root/workspace/pTelescope/xartfull/.meteor/local/build/programs/server/boot.js:249:5
=> Exited with code: 8
```

https://github.com/meteor/meteor/pull/5442

**Comment by SachaG** [comment]
That should've been fixed here: https://github.com/TelescopeJS/Telescope/commit/7be1df6cf81414860a6a812e69ab136633f36fc5 

Are you running the latest version?

**Comment by capensisma** [comment]
I was updating to the last version from 0.25.4 to 0.25.5 with `meteor update` and this happened!

What is this? :)

**Comment by SachaG** [comment]
Are you 100% sure the error is still happening in `0.25.5`?

**Comment by capensisma** [comment]
well, I had to edit that telescope-notifications/lib/herald.js and change that small portion of code nd it's working right now well :) on `0.25.5`

**Comment by aristidesfl** [comment]
Having the same problem

**Comment by aristidesfl** [comment]
The version being used in the Heroku Deploy button seems to work fine though..

**Comment by xavcz** [comment]
Hey, @aristidesfl! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
