### ISSUE TITLE
Https issue with Cloudinary

### ISSUE THREAD

**Issue by AddedLayer** [TelescopeJS/Telescope#1224]
Getting this error: 
Mixed Content: The page at <telescope app url> was loaded over HTTPS, but requested an insecure image <cloudinary image url>. This content should also be served over HTTPS.

Is there anyway there can be a dropdown for http or https in the Cloudinary settings on Telescope?

**Comment by SachaG** [comment]
I'll take a look when I can. But if you want to take a stab at it yourself, all the relevant code is in the telescope-cloudinary package.

**Comment by AddedLayer** [comment]
Thanks. Digging deeper, it seems the the server is outputting the following in the logs:
"at lib/callbacks.js:71:17 Exception in defer callback: Error: When the modifier option is true, validation object must have at least one operator"

This happens "at cachePostThumbnailOnSubmit (lib/server/cloudinary.js:67:11)"

I'm seeing these logs when a new post is coming in. The thumbnail is blank, only when I manually generate a thumbnail, does the caching to Cloudinary work.

**Comment by AddedLayer** [comment]
This is the full trace:

message: Exception in defer callback: 
stack:
Error: When the modifier option is true, validation object must have at least one operator
    at checkModifier (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2293:1)
    at doValidation1 (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2343:1)
    at doValidation (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2758:1)
    at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2793:1)
    at [object Object].doValidate (packages/aldeed_collection2/packages/aldeed_collection2.js:372:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2/packages/aldeed_collection2.js:177:1)
    at cachePostThumbnailOnEdit (lib/server/cloudinary.js:81:11)
    at lib/callbacks.js:73:9
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at lib/callbacks.js:71:17

**Comment by Jarskih** [comment]
I have SSL enabled and I got same problem. Quick fix what worked for me is to edit cloudinary.js:
   
`16: var cachedUrl = result.url;`
To:
`16: var cachedUrl = result.secure_url;`

**Comment by xavcz** [comment]
Fixed on Nova 👍
