### ISSUE TITLE
PostsCommenters error when overriding Header

### ISSUE THREAD

**Issue by schabluk** [TelescopeJS/Telescope#1344]
When I remove this code from my CustomHeader component:
```
          <div className="nav-user">
            {currentUser ? <UsersMenu user={currentUser}/> : <UsersAccountMenu/>}
          </div>
```

I'm getting this error:

```
W20160612-07:56:57.935(2)? (STDERR) Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `PostsCommenters`.
W20160612-07:56:57.936(2)? (STDERR) Error when doing SSR. path:/: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `PostsCommenters`.
W20160612-07:56:57.938(2)? (STDERR) Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `PostsCommenters`.
W20160612-07:56:57.938(2)? (STDERR)     at invariant (/Users/user/project/node_modules/fbjs/lib/invariant.js:38:15)
W20160612-07:56:57.938(2)? (STDERR)     at instantiateReactComponent (/Users/user/project/node_modules/react/lib/instantiateReactComponent.js:85:134)
W20160612-07:56:57.938(2)? (STDERR)     at instantiateChild (/Users/user/project/node_modules/react/lib/ReactChildReconciler.js:29:28)
W20160612-07:56:57.938(2)? (STDERR)     at traverseAllChildrenImpl (/Users/user/project/node_modules/react/lib/traverseAllChildren.js:67:5)
W20160612-07:56:57.938(2)? (STDERR)     at traverseAllChildrenImpl (/Users/user/project/node_modules/react/lib/traverseAllChildren.js:83:23)
W20160612-07:56:57.938(2)? (STDERR)     at traverseAllChildren (/Users/user/project/node_modules/react/lib/traverseAllChildren.js:155:10)
W20160612-07:56:57.938(2)? (STDERR)     at Object.ReactChildReconciler.instantiateChildren (/Users/user/project/node_modules/react/lib/ReactChildReconciler.js:52:5)
W20160612-07:56:57.938(2)? (STDERR)     at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerInstantiateChildren (/Users/user/project/node_modules/react/lib/ReactMultiChild.js:170:41)
W20160612-07:56:57.939(2)? (STDERR)     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/user/project/node_modules/react/lib/ReactMultiChild.js:207:27)
W20160612-07:56:57.939(2)? (STDERR)     at ReactDOMComponent.Mixin._createContentMarkup (/Users/user/project/node_modules/react/lib/ReactDOMComponent.js:611:32)
W20160612-07:58:00.427(2)? (STDERR) WARNING: npm peer requirements not installed:
W20160612-07:58:00.427(2)? (STDERR)  - react@15.1.0 installed, react@^0.14.6 needed
W20160612-07:58:00.427(2)? (STDERR)           
W20160612-07:58:00.427(2)? (STDERR) Read more about installing npm peer dependencies:
W20160612-07:58:00.427(2)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160612-07:58:00.428(2)? (STDERR)                 
```

Is PostsCommenters dependend on Header somehow?

**Comment by SachaG** [comment]
That error usually indicates a syntax error in a component. I would double-check everything and remove code until the error disappears to try and isolate it.
