### ISSUE TITLE
MupX deployment fails. Why?

### ISSUE THREAD

**Issue by kramer65** [TelescopeJS/Telescope#1383]
I'm trying to deploy Telescope to a simple Ubuntu 16.04 server. So I'm using the suggested deployment with MupX. After setting up the mup.json file, I did a `mupx deploy`:

    $ mupx setup
    
    Meteor Up: Production Quality Meteor Deployments
    ------------------------------------------------
    Configuration file : mup.json
    Settings file      : settings.json
    
    
    Started TaskList: Setup (linux)
    [146.185.181.9] - Installing Docker
    [146.185.181.9] - Installing Docker: SUCCESS
    [146.185.181.9] - Setting up Environment
    [146.185.181.9] - Setting up Environment: SUCCESS
    [146.185.181.9] - Copying MongoDB configuration
    [146.185.181.9] - Copying MongoDB configuration: SUCCESS
    [146.185.181.9] - Installing MongoDB
    [146.185.181.9] - Installing MongoDB: SUCCESS

No problems there, so after this I tried a `mupx deploy`, but that ends with an error:

    $ mupx deploy
    
    Meteor Up: Production Quality Meteor Deployments
    ------------------------------------------------
    Configuration file : mup.json
    Settings file      : settings.json
    
    Meteor app path    : /Users/kramer65/dev/repos/Telescope
    Using buildOptions : {}
    nova:rss: updating npm dependencies -- rss...
    
    Changes to your project's package version selections:
    
    reactrouter:react-router-ssr  downgraded from 3.1.4 to 3.1.3
    
    
    Started TaskList: Deploy app 'telescope' (linux)
    [146.185.181.9] - Uploading bundle
    [146.185.181.9] - Uploading bundle: SUCCESS
    [146.185.181.9] - Sending environment variables
    [146.185.181.9] - Sending environment variables: SUCCESS
    [146.185.181.9] - Initializing start script
    [146.185.181.9] - Initializing start script: SUCCESS
    [146.185.181.9] - Invoking deployment process
    [146.185.181.9] - Invoking deployment process: SUCCESS
    [146.185.181.9] - Verifying deployment
    [146.185.181.9] x Verifying deployment: FAILED
    
    	-----------------------------------STDERR-----------------------------------
    	 run:
    	npm WARN deprecated
    	npm WARN deprecated   npm -g install npm@latest
    	npm WARN deprecated
    	npm WARN deprecated (Depending on how Node.js was installed on your system, you
    	npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    	npm WARN deprecated on Windows, run them from an Administrator prompt.)
    	npm WARN deprecated
    	npm WARN deprecated If you're running the version of npm bundled with
    	npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    	npm WARN deprecated will be bundled with a version of npm@2, which has some small
    	npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    	npm WARN deprecated semver behavior.
    	npm WARN package.json meteor-dev-bundle@0.0.0 No description
    	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    
    	> fibers@1.0.8 install /bundle/bundle/programs/server/node_modules/fibers
    	> node build.js || nodejs build.js
    
    	-----------------------------------STDOUT-----------------------------------
    
    	To see more logs type 'mup logs --tail=50'
    
    	----------------------------------------------------------------------------

So I checked what the logs said:

    $ mupx logs --tail=50
    
    Meteor Up: Production Quality Meteor Deployments
    ------------------------------------------------
    Configuration file : mup.json
    Settings file      : settings.json
    
    [146.185.181.9]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
    [146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    [146.185.181.9]     at packages/react-meteor-data/createContainer.jsx:10:16
    [146.185.181.9] npm WARN deprecated This version of npm lacks support for important features,
    [146.185.181.9] npm WARN deprecated such as scoped packages, offered by the primary npm
    [146.185.181.9] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
    [146.185.181.9] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
    [146.185.181.9] npm WARN deprecated
    [146.185.181.9] npm WARN deprecated   npm -g install npm@latest-2
    [146.185.181.9] npm WARN deprecated
    [146.185.181.9] npm WARN deprecated To upgrade to the latest stable version, run:
    [146.185.181.9] npm WARN deprecated
    [146.185.181.9] npm WARN deprecated   npm -g install npm@latest
    [146.185.181.9] npm WARN deprecated
    [146.185.181.9] npm WARN deprecated (Depending on how Node.js was installed on your system, you
    [146.185.181.9] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    [146.185.181.9] npm WARN deprecated on Windows, run them from an Administrator prompt.)
    [146.185.181.9] npm WARN deprecated
    [146.185.181.9] npm WARN deprecated If you're running the version of npm bundled with
    [146.185.181.9] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    [146.185.181.9] npm WARN deprecated will be bundled with a version of npm@2, which has some small
    [146.185.181.9] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    [146.185.181.9] npm WARN deprecated semver behavior.
    [146.185.181.9] npm WARN package.json meteor-dev-bundle@0.0.0 No description
    [146.185.181.9] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    [146.185.181.9] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    [146.185.181.9] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    [146.185.181.9] => Starting meteor app on port:80
    [146.185.181.9] WARNING: npm peer requirements (for react-meteor-data) not installed:
    [146.185.181.9]  - react@15.x not installed.
    [146.185.181.9]  - react-addons-pure-render-mixin@15.x not installed.
    [146.185.181.9]
    [146.185.181.9] Read more about installing npm peer dependencies:
    [146.185.181.9]   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
    [146.185.181.9]
    [146.185.181.9]
    [146.185.181.9] /bundle/bundle/programs/server/node_modules/fibers/future.js:267
    [146.185.181.9] 						throw(ex);
    [146.185.181.9] 						      ^
    [146.185.181.9] Error: Can't find npm module 'react'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
    [146.185.181.9]     at Object.Npm.require (/bundle/bundle/programs/server/boot.js:195:17)
    [146.185.181.9]     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
    [146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
    [146.185.181.9]     at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:5:1)
    [146.185.181.9]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
    [146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    [146.185.181.9]     at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
    [146.185.181.9]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
    [146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    [146.185.181.9]     at packages/react-meteor-data/createContainer.jsx:10:16

In these logs I read something about React not being installed. But as far as I can see, it installs Telescope into a Docker container, and I don't really know how I can install react within that container.

Does anybody have any idea what I can do to fix this?

**Comment by SachaG** [comment]
Weird. It sounds like it's failing to install React, so maybe `npm install` fails. But I'm not sure why that would happen… What if you try on Ubuntu 14.04?

**Comment by xavcz** [comment]
It may be related to the `deployCheckWaitTime` value in your `mup.json` file. Try to increase it to 30 or 60?

**Comment by kramer65** [comment]
@xavcz  - I tried increasing `deployCheckWaitTime` to 120, but unfortunately it still ends in the following error:

```
$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /Users/kramer65/dev/repos/Telescope
Using buildOptions : {}

Started TaskList: Deploy app 'telescope' (linux)
[146.185.181.9] - Uploading bundle
[146.185.181.9] - Uploading bundle: SUCCESS
[146.185.181.9] - Sending environment variables
[146.185.181.9] - Sending environment variables: SUCCESS
[146.185.181.9] - Initializing start script
[146.185.181.9] - Initializing start script: SUCCESS
[146.185.181.9] - Invoking deployment process
[146.185.181.9] - Invoking deployment process: SUCCESS
[146.185.181.9] - Verifying deployment
[146.185.181.9] x Verifying deployment: FAILED

	-----------------------------------STDERR-----------------------------------
	e?
	    at Object.Npm.require (/bundle/bundle/programs/server/boot.js:195:17)
	    at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
	    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
	    at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:5:1)
	    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
	    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
	    at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
	    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
	    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
	    at packages/react-meteor-data/createContainer.jsx:10:16

	=> Redeploying previous version of the app

	-----------------------------------STDOUT-----------------------------------

	To see more logs type 'mup logs --tail=50'

	----------------------------------------------------------------------------
```

with the logs being:

```
$ mupx logs --tail=50

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[146.185.181.9]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
[146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
[146.185.181.9]     at packages/react-meteor-data/createContainer.jsx:10:16
[146.185.181.9] npm WARN deprecated This version of npm lacks support for important features,
[146.185.181.9] npm WARN deprecated such as scoped packages, offered by the primary npm
[146.185.181.9] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[146.185.181.9] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated   npm -g install npm@latest-2
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated To upgrade to the latest stable version, run:
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated   npm -g install npm@latest
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated (Depending on how Node.js was installed on your system, you
[146.185.181.9] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[146.185.181.9] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated If you're running the version of npm bundled with
[146.185.181.9] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[146.185.181.9] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[146.185.181.9] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[146.185.181.9] npm WARN deprecated semver behavior.
[146.185.181.9] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[146.185.181.9] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[146.185.181.9] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[146.185.181.9] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
[146.185.181.9] => Starting meteor app on port:80
[146.185.181.9] WARNING: npm peer requirements (for react-meteor-data) not installed:
[146.185.181.9]  - react@15.x not installed.
[146.185.181.9]  - react-addons-pure-render-mixin@15.x not installed.
[146.185.181.9]
[146.185.181.9] Read more about installing npm peer dependencies:
[146.185.181.9]   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
[146.185.181.9]
[146.185.181.9]
[146.185.181.9] /bundle/bundle/programs/server/node_modules/fibers/future.js:267
[146.185.181.9] 						throw(ex);
[146.185.181.9] 						      ^
[146.185.181.9] Error: Can't find npm module 'react'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
[146.185.181.9]     at Object.Npm.require (/bundle/bundle/programs/server/boot.js:195:17)
[146.185.181.9]     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
[146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
[146.185.181.9]     at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:5:1)
[146.185.181.9]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
[146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
[146.185.181.9]     at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
[146.185.181.9]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
[146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
[146.185.181.9]     at packages/react-meteor-data/createContainer.jsx:10:16
```

Any other ideas?

**Comment by xavcz** [comment]
I found this stackoverlow thread: http://stackoverflow.com/questions/9023672/nodejs-how-to-resolve-cannot-find-module-error

Maybe log into your docker container, remove your node_modules folder and reinstall npm packages?

**Comment by fortunto2** [comment]
hi, i have same error when deploy with mupx

`
....
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
=> Starting meteor app on port:80

/bundle/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						      ^
Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/react/lib/React.js:14:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (/bundle/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
`

**Comment by fortunto2** [comment]
I realized my mistake, try

docker exec -i -t telescope npm install --save react  - in docker
or
npm install --save react   in project folder

**Comment by capensisma** [comment]
Just use Ubuntu 14.04 LTS and it will work like a charm and deploy in seconds!

**Comment by sergimiral** [comment]
Getting the same error here from time to time, sometimes it just deploys correctly.
When it fails and although the log says "redeploying previous version of the app" the browser returns a 502 Bad Gateway error from nginx.

For the record, I'm deploying to an Ubuntu 14.04 so I'm assuming this issue could have nothing to do with the Ubuntu version but more with mupx's settings or configuration (in my case increasing the value of `deployCheckWaitTime ` didn't solve this issue either).

**Comment by kramer65** [comment]
@capensisma and @xavcz - I tried deploying to a fresh Ubuntu 14.04 install with 1GB of memory and `deployCheckWaitTime` set to 120, but it still ends in an error about react not being installed:

```
$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /Users/kramer65/dev/repos/Telescope
Using buildOptions : {}

Started TaskList: Deploy app 'telescope' (linux)
[146.185.181.9] - Uploading bundle
[146.185.181.9] - Uploading bundle: SUCCESS
[146.185.181.9] - Sending environment variables
[146.185.181.9] - Sending environment variables: SUCCESS
[146.185.181.9] - Initializing start script
[146.185.181.9] - Initializing start script: SUCCESS
[146.185.181.9] - Invoking deployment process
[146.185.181.9] - Invoking deployment process: SUCCESS
[146.185.181.9] - Verifying deployment
[146.185.181.9] x Verifying deployment: FAILED

	-----------------------------------STDERR-----------------------------------
	 package.js within the 'modules-runtime' package?
	    at Object.Npm.require (/bundle/bundle/programs/server/boot.js:195:17)
	    at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
	    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
	    at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:5:1)
	    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
	    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
	    at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
	    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
	    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
	    at packages/react-meteor-data/createContainer.jsx:10:16
	-----------------------------------STDOUT-----------------------------------

	To see more logs type 'mup logs --tail=50'

	----------------------------------------------------------------------------
```

The logs now look like this:

```
$ mupx logs --tail=50

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[146.185.181.9]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
[146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
[146.185.181.9]     at packages/react-meteor-data/createContainer.jsx:10:16
[146.185.181.9] npm WARN deprecated This version of npm lacks support for important features,
[146.185.181.9] npm WARN deprecated such as scoped packages, offered by the primary npm
[146.185.181.9] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[146.185.181.9] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated   npm -g install npm@latest-2
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated To upgrade to the latest stable version, run:
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated   npm -g install npm@latest
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated (Depending on how Node.js was installed on your system, you
[146.185.181.9] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[146.185.181.9] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[146.185.181.9] npm WARN deprecated
[146.185.181.9] npm WARN deprecated If you're running the version of npm bundled with
[146.185.181.9] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[146.185.181.9] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[146.185.181.9] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[146.185.181.9] npm WARN deprecated semver behavior.
[146.185.181.9] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[146.185.181.9] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[146.185.181.9] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[146.185.181.9] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
[146.185.181.9] => Starting meteor app on port:80
[146.185.181.9] WARNING: npm peer requirements (for react-meteor-data) not installed:
[146.185.181.9]  - react@15.x not installed.
[146.185.181.9]  - react-addons-pure-render-mixin@15.x not installed.
[146.185.181.9]
[146.185.181.9] Read more about installing npm peer dependencies:
[146.185.181.9]   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
[146.185.181.9]
[146.185.181.9]
[146.185.181.9] /bundle/bundle/programs/server/node_modules/fibers/future.js:267
[146.185.181.9] 						throw(ex);
[146.185.181.9] 						      ^
[146.185.181.9] Error: Can't find npm module 'react'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
[146.185.181.9]     at Object.Npm.require (/bundle/bundle/programs/server/boot.js:195:17)
[146.185.181.9]     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
[146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
[146.185.181.9]     at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:5:1)
[146.185.181.9]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
[146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
[146.185.181.9]     at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
[146.185.181.9]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
[146.185.181.9]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
[146.185.181.9]     at packages/react-meteor-data/createContainer.jsx:10:16
```

Any ideas what the problem could be here?

**Comment by xavcz** [comment]
On which branch are you? Does it run locally after `npm install`?

**Comment by fortunto2** [comment]
**npm install --save modules-runtime**

try to install the module in the project
and then re mupx deploy

**Comment by kramer65** [comment]
@xavcz - I'm on master, on commit `9cc12be 2016-07-04 | test if URL is not empty`

@fortunto2 - I've tried your command, but that gives me a 404: `Registry returned 404 for GET on https://registry.npmjs.org/modules-runtime`.

I had it running on my laptop locally before, but I just tried running `npm install` again, which now fails in `npm WARN react-router-bootstrap@0.23.0 requires a peer of react-router@>=2.0.0 but none was installed.`.

So I cloned the repo in a fresh new folder on the latest commit (`cb448e2 2016-07-06 | Merge pull request #1385 from IlyaSemenov/require_react_15.0`) and ran `npm install`, which ends in:

```
$ npm install
npm WARN react-router-bootstrap@0.23.0 requires a peer of react-router@>=2.0.0 but none was installed.
```
So I can't even get it to run locally anymore. Any more ideas?

**Comment by fortunto2** [comment]
@kramer65  yes sorry, look https://forums.meteor.com/t/error-cant-find-npm-module-react-did-you-forget-to-call-npm-depends-in-package-js-within-the-modules-runtime-package/20416/5

` meteor npm install --save react react-dom react-addons-transition-group
react-addons-css-transition-group react-addons-linked-state-mixin react-addons-create-fragment react-addons-update react-addons-pure-render-mixin react-addons-test-utils react-addons-perf 
`

**Comment by kramer65** [comment]
@fortunto2 - I presume you mean running this command locally? I tried that, but it ends in the following:

```
$ meteor npm install --save react react-dom react-addons-transition-group react-addons-css-transition-group react-addons-linked-state-mixin react-addons-create-fragment react-addons-update react-addons-pure-render-mixin react-addons-test-utils react-addons-perf
Nova@0.0.0 /Users/hielke/dev/repos/Telescope
├── UNMET PEER DEPENDENCY react@15.0.2
├── react-addons-create-fragment@15.2.0
├── react-addons-css-transition-group@15.2.0
├── react-addons-linked-state-mixin@15.2.0
├── react-addons-perf@15.2.0
├── react-addons-pure-render-mixin@15.0.2
├── react-addons-test-utils@15.2.0
├── react-addons-transition-group@15.2.0
├── react-addons-update@15.2.0
├── react-dom@15.0.2
└── UNMET PEER DEPENDENCY react-router@3.0.0-alpha.1

npm WARN react-router-bootstrap@0.23.0 requires a peer of react-router@>=2.0.0 but none was installed.
npm WARN react-addons-linked-state-mixin@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-test-utils@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-css-transition-group@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-create-fragment@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-transition-group@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-update@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-addons-perf@15.2.0 requires a peer of react@^15.2.0 but none was installed.
```

**Comment by fortunto2** [comment]
yes local, and then try - mupx deploy
but need first solve "UNMET PEER DEPENDENCY"
may be
npm install --save react@15.0.2
npm install --save react-router@3.0.0-alpha.1

**Comment by kramer65** [comment]
@fortunto2 - Yes, that fixed it! Thanks!
