### ISSUE TITLE
Mongo in Nova: performance, index, oplog

### ISSUE THREAD

**Issue by fortunto2** [TelescopeJS/Telescope#1404]
Hi,
I have a performance problem.
I imported the database of 100,000 posts and 250,000 users.
The site is running slowly.
new.life2film.com

How can I find out what the performance bottleneck?

Kadira say me this error

Internal Server Error - Exception in setInterval callback:

```
message: Exception in setInterval callback: 
stack:
MongoError: cursor killed or timed out
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:420:15)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:986:47)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1020:22)
    at Cursor.(anonymous function) (packages/mongo/mongo_driver.js:869:44)
    at Cursor.MeteorCursor.(anonymous function) (packages/peerlibrary_reactive-mongo/packages/peerlibrary_reactive-mongo.js:78:1)
    at Cursor.cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:126:1)
    at Cursor.kadira_Cursor_forEach [as forEach] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:63:1)
    at packages/nova:voting/lib/server/cron.js:28:38
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    - - - - -
    at Object.toError (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/cursor.js:847:31
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
```

**Comment by capensisma** [comment]
Dude how did you get `database of 100,000 posts and 250,000 users.` ??? and also did you use a dedicated database or just the local one?

**Comment by fortunto2** [comment]
@capensisma 
i deployd to AWS EC2 (medium 4 gb) with mupx (docker for mongo and nginx)

my db statistics
```
{
    "db" : "novalf",
    "collections" : 18,
    "objects" : 331607,
    "avgObjSize" : 1135.0653876426,
    "dataSize" : 376395628.0,
    "storageSize" : 145014784.0,
    "numExtents" : 0,
    "indexes" : 42,
    "indexSize" : 29622272.0,
    "ok" : 1.0
}
```

and Post collection
```
{
    "ns" : "novalf.posts",
    "count" : 90823,
    "size" : 68088700,
    "avgObjSize" : 749,
    "storageSize" : 21852160,
    "capped" : false,
    "wiredTiger" : {
        "metadata" : {
            "formatVersion" : 1
        },
        "creationString" : "allocation_size=4KB,app_metadata=(formatVersion=1),block_allocation=best,block_compressor=snappy,cache_resident=0,checksum=on,colgroups=,collator=,columns=,dictionary=0,encryption=(keyid=,name=),exclusive=0,extractor=,format=btree,huffman_key=,huffman_value=,immutable=0,internal_item_max=0,internal_key_max=0,internal_key_truncate=,internal_page_max=4KB,key_format=q,key_gap=10,leaf_item_max=0,leaf_key_max=0,leaf_page_max=32KB,leaf_value_max=64MB,log=(enabled=),lsm=(auto_throttle=,bloom=,bloom_bit_count=16,bloom_config=,bloom_hash_count=8,bloom_oldest=0,chunk_count_limit=0,chunk_max=5GB,chunk_size=10MB,merge_max=15,merge_min=0),memory_page_max=10m,os_cache_dirty_max=0,os_cache_max=0,prefix_compression=0,prefix_compression_min=4,source=,split_deepen_min_child=0,split_deepen_per_child=0,split_pct=90,type=file,value_format=u",
        "type" : "file",
        "uri" : "statistics:table:collection-369--6565001890547854487",
        "LSM" : {
            "bloom filter false positives" : 0,
            "bloom filter hits" : 0,
            "bloom filter misses" : 0,
            "bloom filter pages evicted from cache" : 0,
            "bloom filter pages read into cache" : 0,
            "bloom filters in the LSM tree" : 0,
            "chunks in the LSM tree" : 0,
            "highest merge generation in the LSM tree" : 0,
            "queries that could have benefited from a Bloom filter that did not exist" : 0,
            "sleep for LSM checkpoint throttle" : 0,
            "sleep for LSM merge throttle" : 0,
            "total size of bloom filters" : 0
        },
        "block-manager" : {
            "allocations requiring file extension" : 0,
            "blocks allocated" : 6649,
            "blocks freed" : 2689,
            "checkpoint size" : 34213888,
            "file allocation unit size" : 4096,
            "file bytes available for reuse" : 151552,
            "file magic number" : 120897,
            "file major version number" : 1,
            "file size in bytes" : 21852160,
            "minor version number" : 0
        },
        "btree" : {
            "btree checkpoint generation" : 10903,
            "column-store fixed-size leaf pages" : 0,
            "column-store internal pages" : 0,
            "column-store variable-size RLE encoded values" : 0,
            "column-store variable-size deleted values" : 0,
            "column-store variable-size leaf pages" : 0,
            "fixed-record size" : 0,
            "maximum internal page key size" : 368,
            "maximum internal page size" : 4096,
            "maximum leaf page key size" : 2867,
            "maximum leaf page size" : 32768,
            "maximum leaf page value size" : 67108864,
            "maximum tree depth" : 4,
            "number of key/value pairs" : 0,
            "overflow pages" : 0,
            "pages rewritten by compaction" : 0,
            "row-store internal pages" : 0,
            "row-store leaf pages" : 0
        },
        "cache" : {
            "bytes currently in the cache" : 76894160,
            "bytes read into cache" : 68954257,
            "bytes written from cache" : 43603234,
            "checkpoint blocked page eviction" : 0,
            "data source pages selected for eviction unable to be evicted" : 0,
            "hazard pointer blocked page eviction" : 0,
            "in-memory page passed criteria to be split" : 0,
            "in-memory page splits" : 0,
            "internal pages evicted" : 0,
            "internal pages split during eviction" : 0,
            "leaf pages split during eviction" : 0,
            "modified pages evicted" : 0,
            "overflow pages read into cache" : 0,
            "overflow values cached in memory" : 0,
            "page split during eviction deepened the tree" : 0,
            "page written requiring lookaside records" : 0,
            "pages read into cache" : 2457,
            "pages read into cache requiring lookaside entries" : 0,
            "pages written from cache" : 4009,
            "pages written requiring in-memory restoration" : 0,
            "unmodified pages evicted" : 0
        },
        "compression" : {
            "compressed pages read" : 2442,
            "compressed pages written" : 1361,
            "page written failed to compress" : 0,
            "page written was too small to compress" : 2648,
            "raw compression call failed, additional data available" : 0,
            "raw compression call failed, no additional data available" : 0,
            "raw compression call succeeded" : 0
        },
        "cursor" : {
            "bulk-loaded cursor-insert calls" : 0,
            "create calls" : 224,
            "cursor-insert key and value bytes inserted" : 1120245,
            "cursor-remove key bytes removed" : 0,
            "cursor-update value bytes updated" : 0,
            "insert calls" : 1445,
            "next calls" : 5483252,
            "prev calls" : 1,
            "remove calls" : 0,
            "reset calls" : 1978183198.0,
            "restarted searches" : 0,
            "search calls" : 212202534685.0,
            "search near calls" : 43209,
            "truncate calls" : 0,
            "update calls" : 0
        },
        "reconciliation" : {
            "dictionary matches" : 0,
            "fast-path pages deleted" : 0,
            "internal page key bytes discarded using suffix compression" : 2,
            "internal page multi-block writes" : 0,
            "internal-page overflow keys" : 0,
            "leaf page key bytes discarded using prefix compression" : 0,
            "leaf page multi-block writes" : 0,
            "leaf-page overflow keys" : 0,
            "maximum blocks required for a page" : 0,
            "overflow values written" : 0,
            "page checksum matches" : 0,
            "page reconciliation calls" : 4009,
            "page reconciliation calls for eviction" : 0,
            "pages deleted" : 0
        },
        "session" : {
            "object compaction" : 0,
            "open cursor count" : 14
        },
        "transaction" : {
            "update conflicts" : 0
        }
    },
    "nindexes" : 2,
    "totalIndexSize" : 3338240,
    "indexSizes" : {
        "_id_" : 1855488,
        "status_1_postedAt_1" : 1482752
    },
    "ok" : 1.0
}
```

Post shema example 

```
{
    "_id" : "baaafshx",
    "status" : 2,
    "filmUrl" : "251145/baaafshx.mp4",
    "excerpt" : "",
    "sticky" : false,
    "clickCount" : 0,
    "inactive" : 0,
    "duration" : 58,
    "thumbnailUrl" : "251145/baaafshx.mp4.jpg",
    "createdAt" : ISODate("2016-07-13T14:22:23.000Z"),
    "author" : "ира зарубина",
    "music" : {
        "musicGalleryId" : "20",
        "musicTitle" : "Just Dreaming",
        "bpm" : 116,
        "musicArtist" : "Danie Nel",
        "musicLink" : "/music/20",
        "duration" : "207.39"
    },
    "proHD" : false,
    "body" : "",
    "isPublic" : true,
    "tags" : [ 
        "frends"
    ],
    "userId" : "251145",
    "shootingDate" : ISODate("2016-07-13T00:00:00.000Z"),
    "htmlBody" : "",
    "job" : {
        "sound" : false,
        "compression" : 1,
        "format" : "640x360",
        "pathup" : "media/user_251145/up/baaafshx",
        "rendertime" : 96,
        "mysql_id" : 256883,
        "speed" : 1.0
    },
    "slug" : "baaafshx",
    "categories" : [ 
        6
    ],
    "viewCount" : 2,
    "postedAt" : ISODate("2016-07-13T14:22:23.000Z"),
    "teamplate" : "1",
    "url" : "",
    "title" : "История",
    "lastCommentedAt" : ""
}
```

**Comment by SachaG** [comment]
I have to say I haven't dealt with a site that big before… Are you running Mongo with Oplog enabled?

**Comment by capensisma** [comment]
@fortunto2 you need to use a dedicated mongodb database like compose.io or mongodb because you have a lot of data and you can't use the local docker mongodb or it will crash and also be versy slow 

local mongodb is for testing or small apps!!!

compose.io/articles/meteor-and-compose-a-beginners-guide-to-using-them-together/

and how did you get those stats??

**Comment by capensisma** [comment]
Or use `MongoDB Atlas`  https://www.mongodb.com/cloud

@SachaG :) he might have scrapped the data or something but his content seems legit and lot of real users...

**Comment by fortunto2** [comment]
@SachaG  No, but I'll try to enable oplog

@capensisma 
thanks ok i will look...
but now i use only Amazon AWS for deploy all servers
for stat 
db.getCollection('posts').stats()
db.stats()

@SachaG 
I thought may be a problem in the indexes for POST collection
need to optimize the sorting by date, and other fields, I experiment until

Look
db.getCollection('posts').find({}).sort({createdAt: -1})
give me
```
Error: error: {
	"waitedMS" : NumberLong(0),
	"ok" : 0,
	"errmsg" : "Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.",
	"code" : 96
}
```

**Comment by fortunto2** [comment]
add index for Post
    {
        "v" : 1,
        "key" : {
            "createdAt" : -1
        },
        "name" : "createdAtDesc",
        "ns" : "novalf.posts"
    }
and query work well
` db.getCollection('posts').find({}).sort({createdAt: -1})`

@SachaG please help
what raw mongo query for this code 

```
      <ListContainer
        collection={Posts}
        publication="posts.list"
        selector={selector}
        options={options}
        terms={params}
        joins={Posts.getJo      <ListContainer
        collection={Posts}
        publication="posts.list"
        selector={selector}
        options={options}
        terms={params}
        joins={Posts.getJoins()}
        component={Telescope.components.PostsList}
        cacheSubscription={false}
        listId={params.listId}
        limit={Telescope.settings.get("postsPerPage", 10)}
      />ins()}
        component={Telescope.components.PostsList}
        cacheSubscription={false}
        listId={params.listId}
        limit={Telescope.settings.get("postsPerPage", 10)}
      />
```

**Comment by SachaG** [comment]
Creating indexes can help, but using oplog will already help a lot with your performances.

**Comment by fortunto2** [comment]
@SachaG yes ok, but i think index important
I'll try to understand with indexes and write its decision ...

**Comment by fortunto2** [comment]
well done,

i set oplog for mupx
https://acrofever.com/blog/adding-oplog-tailing-to-a-meteor-app-using-mup-mupx.html

and create this index
```
[
    {
        "v" : 1,
        "key" : {
            "_id" : 1
        },
        "name" : "_id_",
        "ns" : "novalf.posts"
    },
    {
        "v" : 1,
        "key" : {
            "sticky" : -1,
            "postedAt" : -1,
            "status" : 1,
            "category" : 1
        },
        "name" : "category",
        "ns" : "novalf.posts"
    },
    {
        "v" : 1,
        "key" : {
            "sticky" : -1,
            "postedAt" : -1,
            "_id" : -1,
            "status" : 1
        },
        "name" : "new_id",
        "ns" : "novalf.posts"
    },
    {
        "v" : 1,
        "key" : {
            "sticky" : -1,
            "postedAt" : -1,
            "_id" : -1,
            "status" : 1,
            "category" : 1
        },
        "name" : "category_id",
        "ns" : "novalf.posts"
    },
    {
        "v" : 1,
        "key" : {
            "sticky" : -1,
            "score" : -1,
            "_id" : -1,
            "status" : 1
        },
        "name" : "top_id",
        "ns" : "novalf.posts"
    },
    {
        "v" : 1,
        "key" : {
            "sticky" : -1,
            "postedAt" : -1,
            "status" : 1
        },
        "name" : "new",
        "ns" : "novalf.posts"
    },
    {
        "v" : 1,
        "key" : {
            "sticky" : -1,
            "baseScore" : -1,
            "status" : 1
        },
        "name" : "best",
        "ns" : "novalf.posts"
    },
    {
        "v" : 1,
        "key" : {
            "sticky" : -1,
            "score" : -1,
            "status" : 1
        },
        "name" : "top",
        "ns" : "novalf.posts"
    },
    {
        "v" : 1,
        "key" : {
            "postedAt" : 1,
            "status" : 1
        },
        "name" : "status_1_postedAt_1",
        "ns" : "novalf.posts"
    }
]
```

and it is important to change the status and category, putting the index value down
http://blog.mlab.com/2012/06/cardinal-ins/
