### ISSUE TITLE
internal error when edit post or create post 

### ISSUE THREAD

**Issue by guo** [TelescopeJS/Telescope#1413]
Using the latest code in master branch, 7/27, post editing and creating failed because of internal server errors.

It could be temporarily fixed it by adding a check before getTime(). 
```
function PostsNewSetFuture (post, user) {
  if (post.postedAt && post.createdAt) {
    post.isFuture = post.postedAt.getTime() > post.createdAt.getTime() + 1000; // round up to the second 
  } else {
    post.isFuture = false;
  }
  
  return post;
}
```
Stacktrace: 
```
Exception while invoking method 'posts.new' { stack: 'TypeError: Cannot call method \'getTime\' of undefined\n   
at PostsNewSetFuture (packages/nova:posts/lib/callbacks.js:227:33)\n    
at packages/nova:lib/lib/callbacks.js:59:23\n    at Array.reduce (native)\n    
at Object.Telescope.callbacks.run (packages/nova:lib/lib/callbacks.js:55:22)\n  
 at Object._collection2.default.methods.new (packages/nova:posts/lib/methods.js:22:30)\n    
at [object Object].postsNew (packages/nova:posts/lib/methods.js:104:12)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)\n    at packages/ddp-server/livedata_server.js:711:19\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)',
```

**Comment by SachaG** [comment]
Sorry about that, you can use the devel branch for now.

**Comment by guo** [comment]
I saw it was fixed in devel. Thanks! Closing.
