### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by pixelpunch** [TelescopeJS/Telescope#1439]
Hi,

I am on Meteor 1.4.1.1; npm 3.10.6; react 15.0.1. No other errors except this. The App doesn't start 
```          
W20160903-17:00:54.699(0)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160903-17:00:54.700(0)? (STDERR)                                             throw(ex);
W20160903-17:00:54.708(0)? (STDERR)                                             ^
W20160903-17:00:54.709(0)? (STDERR)           
W20160903-17:00:54.711(0)? (STDERR) ReferenceError: window is not defined
W20160903-17:00:54.809(0)? (STDERR)     at supportsPopstateOnHashchange (/home/ubuntu/workspace/Telescope/node_modules/history/lib/DOMUtils.js:39:10)
W20160903-17:00:54.810(0)? (STDERR)     at Object.<anonymous> (/home/ubuntu/workspace/Telescope/node_modules/history/lib/BrowserProtocol.js:17:75)
W20160903-17:00:54.945(0)? (STDERR)     at Module._compile (module.js:409:26)
W20160903-17:00:54.946(0)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20160903-17:00:54.947(0)? (STDERR)     at Module.load (module.js:343:32)
W20160903-17:00:55.069(0)? (STDERR)     at Module.Mp.load (/home/ubuntu/.meteor/packages/babel-compiler/.6.9.1.qmu614++os+web.browser+web.cordova/npm/node_modules/reify/node/runtime.js:16:23)
W20160903-17:00:55.070(0)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160903-17:00:55.071(0)? (STDERR)     at Module.require (module.js:353:17)
W20160903-17:00:55.156(0)? (STDERR)     at require (internal/module.js:12:17)
W20160903-17:00:55.157(0)? (STDERR)     at Object.<anonymous> (/home/ubuntu/workspace/Telescope/node_modules/history/lib/createBrowserHistory.js:13:24)
=> Exited with code: 1```

**Comment by xavcz** [comment]
Quoting you from the [Slack channel](http://slack.telescopeapp.org): 
> I worked with a fresh meteor installation, works like a charm. :)

I'm closing this.
