### ISSUE TITLE
Deployment issue on Digital Ocean 

### ISSUE THREAD

**Issue by nishantmendiratta** [TelescopeJS/Telescope#1494]
Increased deployCheckWaitTime to 100 still getting error following are the logs 

```
mup setup && mup deploy --settings settings.json

Started TaskList: Setup Docker
[139.59.20.113] - setup docker
[139.59.20.113] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[139.59.20.113] - Setup Environment

Started TaskList: Setup Mongo
[139.59.20.113] - setup environment
[139.59.20.113] - setup environment: SUCCESS
[139.59.20.113] - copying mongodb.conf
[139.59.20.113] - copying mongodb.conf: SUCCESS
[139.59.20.113] - Setup Environment: SUCCESS

Started TaskList: Start Mongo
[139.59.20.113] - start mongo
[139.59.20.113] - start mongo: SUCCESS
Building App Bundle Locally

Started TaskList: Pushing Meteor
[139.59.20.113] - Pushing Meteor App Bundle to The Server
[139.59.20.113] - Pushing Meteor App Bundle to The Server: SUCCESS
[139.59.20.113] - Pushing the Startup Script
[139.59.20.113] - Pushing the Startup Script: SUCCESS

Started TaskList: Configuring  Meteor Environment Variables
[139.59.20.113] - Sending Environment Variables
[139.59.20.113] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[139.59.20.113] - Start Meteor
[139.59.20.113] - Start Meteor: SUCCESS
[139.59.20.113] - Verifying Deployment
[139.59.20.113] x Verifying Deployment: FAILED

	-----------------------------------STDERR-----------------------------------
	package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
	=> Starting meteor app on port:80

	assert.js:93
	  throw new assert.AssertionError({
	        ^
	AssertionError: "undefined" === "function"
	    at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
	    at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Module.require (module.js:364:17)
	    at require (module.js:380:17)
	    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
	    at Module._compile (module.js:456:26)

	=> Redeploying previous version of the app

	-----------------------------------STDOUT-----------------------------------

	To see more logs type 'mup logs --tail=50'
```

**Comment by xavcz** [comment]
Are you running on Node 4.x.x ? (`node -v`) Are you using mup 1.0.3 or above? Did you use `abernix:meteord/base` docker image? 

See an example of `mup.js` : https://gist.github.com/xavcz/6ddc2bb6f67fe0936c8328ab3314641d

**Comment by nishantmendiratta** [comment]
Thanks for the quick response. Adding `dockerImage: 'abernix/meteord:base'` solved the problem.

cheers, (Y)

**Comment by xavcz** [comment]
Awesome 😄
