### ISSUE TITLE
Receiving an error on 'error.accounts.Rating must be a number'

### ISSUE THREAD

**Issue by manriquef** [TelescopeJS/Telescope#1557]
For some reason when developing on my macbook I get this error. My windows machine is just fine. I even tried to delete the project and meteor install and start over but it continues to persist. Any help is appreciated.

Exception while invoking method 'createUser' Error: Rating must be a number
at getErrorObject (packages/aldeed_collection2-core.js:480:15)
at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1326:25)
at _createUser (packages/accounts-password/password_server.js:1009:25)
at packages/accounts-password/password_server.js:1040:20
at tryLoginMethod (packages/accounts-base/accounts_server.js:248:14)
at AccountsServer.Ap._loginMethod (packages/accounts-base/accounts_server.js:381:5)
at [object Object].createUser (packages/accounts-password/password_server.js:1026:19)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1712:12)
Sanitized and reported to the client as: Rating must be a number [400]

**Comment by xavcz** [comment]
``` Rating must be a number```

`rating` is a custom field of yours on `Users`?

Can you paste here code related to this `rating` field / users callback ?

**Comment by manriquef** [comment]
Hi Xavier,

It just dawned on me what the problem was, my head wasn't in the game and just resolved it. It was related to my custom field as you stated. A rookie mistake. I really appreciate you taking the time out to help me!
