### ISSUE TITLE
Users administration page not loading after deletion of invited user

### ISSUE THREAD

**Issue by andredasilvapinto** [TelescopeJS/Telescope#260]
I'm getting these errors in the browser console:

```
Exception from Deps recompute: TypeError: Cannot read property 'username' of undefined
    at getUserName (http://DOMAIN.meteor.com/def11d281a2952dbb07b845ebc08de9a8b2a122e.js:22:13578)
    at getProfileUrl (http://DOMAIN.meteor.com/def11d281a2952dbb07b845ebc08de9a8b2a122e.js:22:13872)
    at Object.Template.user_item.helpers.getInvitedUserProfileUrl (http://DOMAIN.meteor.com/def11d281a2952dbb07b845ebc08de9a8b2a122e.js:23:13633)
    at s (http://DOMAIN.meteor.com/def11d281a2952dbb07b845ebc08de9a8b2a122e.js:10:20760)
    at u (http://DOMAIN.meteor.com/def11d281a2952dbb07b845ebc08de9a8b2a122e.js:10:20992)
    at http://DOMAIN.meteor.com/def11d281a2952dbb07b845ebc08de9a8b2a122e.js:10:21511
    at Object.e.labelBranch (http://DOMAIN.meteor.com/def11d281a2952dbb07b845ebc08de9a8b2a122e.js:10:11827)
    at m (http://DOMAIN.meteor.com/def11d281a2952dbb07b845ebc08de9a8b2a122e.js:10:21366)
    at http://DOMAIN.meteor.com/def11d281a2952dbb07b845ebc08de9a8b2a122e.js:10:21484
    at Array.forEach (native) def11d281a2952dbb07b845ebc08de9a8b2a122e.js:1
4
Uncaught MinimongoError: Mod on _id not allowed 
```

I'm using meteor 0.7.1.2 (so I can claim domains on meteor.com)

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! 👍
