### ISSUE TITLE
bug fetching from rss

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#673]
hello,

I have an alternate error sometimes when I'm trying to fetching from RSS.

In particular I'm trying to fetch Youtube videos using [public feed rss per each channel](http://lifehacker.com/how-to-turn-youtube-channels-into-subscribable-podcasts-496976976). Normally works fine, but some channels are not possible to fetch. In console the error is:

in server side:

```javascript
[zombts.com] Exception while invoking method 'fetchFeeds' TypeError: Cannot call method 'replace' of undefined[zombts.com]
[zombts.com]     at Object.decode (/opt/zombts/app/programs/server/npm/telescope-post-by-feed/node_modules/he/he.js:221:15)[zombts.com]
[zombts.com]     at packages/telescope-post-by-feed/lib/server/fetch_feeds.js:28:1[zombts.com]
[zombts.com]     at Array.forEach (native)[zombts.com]
[zombts.com]     at FeedHandler.handleFeed [as _callback] (packages/telescope-post-by-feed/lib/server/fetch_feeds.js:18:1)[zombts.com]
[zombts.com]     at FeedHandler.DomHandler._handleCallback.DomHandler.onerror (/opt/zombts/app/programs/server/npm/telescope-post-by-feed/node_modules/htmlparser2/node_modules/domhandler/index.js:51:8)
    at FeedHandler.onend (/opt/zombts/app/programs/server/npm/telescope-post-by-feed/node_modules/htmlparser2/lib/FeedHandler.js:90:39)
    at Parser.onend (/opt/zombts/app/programs/server/npm/telescope-post-by-feed/node_modules/htmlparser2/lib/Parser.js:307:32)
    at Tokenizer._finish (/opt/zombts/app/programs/server/npm/telescope-post-by-feed/node_modules/htmlparser2/lib/Tokenizer.js:838:12)
    at Tokenizer.end (/opt/zombts/app/programs/server/npm/telescope-post-by-feed/node_modules/htmlparser2/lib/Tokenizer.js:829:25)
    at Parser.end (/opt/zombts/app/programs/server/npm/telescope-post-by-feed/node_modules/htmlparser2/lib/Parser.js:335:18)
    at packages/telescope-post-by-feed/lib/server/fetch_feeds.js:73:1
```

in client side:

```javascript
Error invoking Method 'fetchFeeds': Internal server error [500]
```

any idea?

**Comment by delgermurun** [comment]
@Kikobeats Give me RSS url that raises error, please.

**Comment by SachaG** [comment]
It sounds like maybe the post-by-feed package is assuming that the `item.description` fields exists when it doesn't? But yeah the specific URL would be useful.

**Comment by Kikobeats** [comment]
@delgermurun for example this

https://gdata.youtube.com/feeds/api/users/UCpalEleA0JfTYgwocI-JoFg/uploads

(between others)

@SachaG yes, I think that is something like these

**Comment by SachaG** [comment]
I just tried that feed and I didn't get any error?

**Comment by delgermurun** [comment]
I tried too and works fine. By the way, I sent PR that checks description exists or not.

**Comment by Kikobeats** [comment]
I tried locally with debug mode and item.description the problem is `item.description`.

before:

```javascript
I20150106-11:26:35.245(1)? { id: 'http://gdata.youtube.com/feeds/api/videos/oDypCGzbv-U',
I20150106-11:26:35.245(1)?   title: 'Experimental &amp; Bauchklang Freestyle @ Human Beatbox Festival',
I20150106-11:26:35.246(1)?   link: 'https://www.youtube.com/watch?v=oDypCGzbv-U&amp;feature=youtube_gdata',
I20150106-11:26:35.246(1)?   pubDate: Tue Jun 10 2014 05:28:34 GMT+0200 (CEST) }
I20150106-11:26:35.251(1)? Exception while invoking method 'fetchFeeds' TypeError: Cannot call method 'replace' of undefined
I20150106-11:26:35.252(1)?     at Object.decode (/Users/josefranciscoverdugambin/Projects/zombts/zombts.com/packages/telescope-post-by-feed/.npm/package/node_modules/he/he.js:221:15)
I20150106-11:26:35.252(1)?     at packages/telescope-post-by-feed/lib/server/fetch_feeds.js:31:1
I20150106-11:26:35.252(1)?     at Array.forEach (native)
I20150106-11:26:35.252(1)?     at FeedHandler.handleFeed [as _callback] (packages/telescope-post-by-feed/lib/server/fetch_feeds.js:18:1)
I20150106-11:26:35.252(1)?     at FeedHandler.DomHandler._handleCallback.DomHandler.onerror (/Users/josefranciscoverdugambin/Projects/zombts/zombts.com/packages/telescope-post-by-feed/.npm/package/node_modules/htmlparser2/node_modules/domhandler/index.js:51:8)
I20150106-11:26:35.253(1)?     at FeedHandler.onend (/Users/josefranciscoverdugambin/Projects/zombts/zombts.com/packages/telescope-post-by-feed/.npm/package/node_modules/htmlparser2/lib/FeedHandler.js:90:39)
I20150106-11:26:35.253(1)?     at Parser.onend (/Users/josefranciscoverdugambin/Projects/zombts/zombts.com/packages/telescope-post-by-feed/.npm/package/node_modules/htmlparser2/lib/Parser.js:307:32)
I20150106-11:26:35.253(1)?     at Tokenizer._finish (/Users/josefranciscoverdugambin/Projects/zombts/zombts.com/packages/telescope-post-by-feed/.npm/package/node_modules/htmlparser2/lib/Tokenizer.js:838:12)
I20150106-11:26:35.253(1)?     at Tokenizer.end (/Users/josefranciscoverdugambin/Projects/zombts/zombts.com/packages/telescope-post-by-feed/.npm/package/node_modules/htmlparser2/lib/Tokenizer.js:829:25)
I20150106-11:26:35.253(1)?     at Parser.end (/Users/josefranciscoverdugambin/Projects/zombts/zombts.com/packages/telescope-post-by-feed/.npm/package/node_modules/htmlparser2/lib/Parser.js:335:18)
```

after the item is added and I think that embeddly get the description scrapping the URL
