### ISSUE TITLE
MongoError digest view

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#679]
When my app tried to render `/digest` view:

```javascript

[178.62.99.49] error on fast-rendering path: /digest ; error: MongoError: Can't canonicalize query: BadValue bad sort specification[178.62.99.49]
[178.62.99.49]     at Object.Future.wait (/opt/zombts/app/programs/server/node_modules/fibers/future.js:326:15)[178.62.99.49]
[178.62.99.49]     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:885:1)[178.62.99.49]
[178.62.99.49]     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:919:1)[178.62.99.49]
[178.62.99.49]     at [object Object]._.extend.map (packages/mongo/mongo_driver.js:929:1)[178.62.99.49]
    at [object Object]._.extend.fetch (packages/mongo/mongo_driver.js:953:1)
    at [object Object].Cursor.(anonymous function) (packages/mongo/mongo_driver.js:768:1)
    at [object Object].cursorProto.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/db.js:100:1)
    at [object Object].kadira_Cursor_fetch [as fetch] (packages/meteorhacks:kadira/lib/profile/set_labels.js:75:1)
    at packages/meteorhacks:fast-render/lib/server/context.js:84:1
    at Array.forEach (native)
    - - - - -
    at Object.toError (/opt/zombts/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at /opt/zombts/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:686:54
[178.62.99.49]     at Cursor.close (/opt/zombts/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:969:5)
    at commandHandler (/opt/zombts/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:686:21)
    at /opt/zombts/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1843:9
    at Server.Base._callHandler (/opt/zombts/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /opt/zombts/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at [object Object].MongoReply.parseBody (/opt/zombts/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/opt/zombts/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at [object Object[178.62.99.49] ].emit (events.js:95:17)
[178.62.99.49] Exception in queued task: MongoError: Can't canonicalize query: BadValue bad sort specification[178.62.99.49]
[178.62.99.49]     at Object.Future.wait (/opt/zombts/app/programs/server/node_modules/fibers/future.js:326:15)[178.62.99.49]
[178.62.99.49]     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:885:1)[178.62.99.49]
[178.62.99.49]     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:919:1)[178.62.99.49]
[178.62.99.49]     at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:968:1)[178.62.99.49]
[178.62.99.49]     at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:144:1)
    at [object Object].proto._pollMongo (packages/meteorhacks:kadira/lib/hijack/wrap_observers.js:23:1)
    at Object.task (packages/mongo/polling_observe_driver.js:85:1)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:145:1)
    at packages/meteor/fiber_helpers.js:123:1
```

:(

**Comment by SachaG** [comment]
Sounds similar to https://github.com/meteor/meteor/issues/3414

Maybe leave a message in that thread?
