### ISSUE TITLE
v0.12.0 deploying issues

### ISSUE THREAD

**Issue by thinkxl** [TelescopeJS/Telescope#688]
```
[104.131.7.145] - Uploading bundle
[104.131.7.145] ✔ Uploading bundle: SUCCESS
[104.131.7.145] - Setting up Environment Variables
[104.131.7.145] ✔ Setting up Environment Variables: SUCCESS
[104.131.7.145] - Invoking deployment process
[104.131.7.145] ✘ Invoking deployment process: FAILED

        -----------------------------------STDERR-----------------------------------
         spawn args   '-Dmodule_root_dir=/opt/frontendsapp/tmp/bundle/programs/server/npm/sacha:juice/node_modules/juice/node_modules/jsdom/node_modules/contextify',
        gyp info spawn args   '--depth=.',
        gyp info spawn args   '--no-parallel',
        gyp info spawn args   '--generator-output',
        gyp info spawn args   'build',
        gyp info spawn args   '-Goutput_dir=.' ]
        gyp info spawn make
        gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
        gyp info ok
        npm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
        Latest deployment failed! Reverted back to the previous version
Latest deployment failed! Reverted back to the previous version.
        -----------------------------------STDOUT-----------------------------------
        mp/bundle/programs/server/npm/sacha:juice/node_modules/juice/node_modules/jsdom/node_modules/contextify/build'

        > fibers@1.0.1 install /opt/frontendsapp/tmp/bundle/programs/server/node_modules/fibers
        > node ./build.js

        `linux-x64-v8-3.14` exists; testing
        Binary is fine; exiting
        underscore@1.5.2 node_modules/underscore

        eachline@2.3.3 node_modules/eachline
        └── type-of@2.0.1

        semver@4.1.0 node_modules/semver

        chalk@0.5.1 node_modules/chalk
        ├── escape-string-regexp@1.0.2
        ├── ansi-styles@1.1.0
        ├── supports-color@0.2.0
        ├── has-ansi@0.1.0 (ansi-regex@0.2.1)
        └── strip-ansi@0.3.0 (ansi-regex@0.2.1)

        source-map-support@0.2.8 node_modules/source-map-support
        └── source-map@0.1.32 (amdefine@0.1.0)

        fibers@1.0.1 node_modules/fibers
        Waiting for MongoDB to initialize. (5 minutes)
        connected
        frontendsapp stop/waiting
        frontendsapp start/running, process 30478
        Waiting for 15 seconds while app is booting up
        Checking is app booted or not?
        frontendsapp stop/waiting
        frontendsapp start/running, process 30540
        ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'frontendsapp' (linux)
```

**Comment by thinkxl** [comment]
it runs well on my computer

**Comment by thinkxl** [comment]
repo url: https://github.com/FrontendsNews/Telescope

**Comment by thinkxl** [comment]
logs

```
[34m[1m
Meteor Up: Production Quality Meteor Deployments[22m[39m
[34m[1m------------------------------------------------
[22m[39m
[104.131.7.145] error: Script restart attempt #13
Meteor requires Node v0.10.33 or later.
error: Forever detected script exited with code: 1
[MailChimp] Error: MailChimp Options have not been set in your settings.json file.
Kadira: completed instrumenting the app
Starting artwells:queue for Herald
{"line":"52","file":"synced-cron-server.js","message":"SyncedCron: scheduled \"Schedule newsletter\" next run @Mon Jan 12 2015 00:00:00 GMT-0500 (EST)","time":{"$date":1420820165671},"level":"info"}
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated
[104.131.7.145] spiderable: phantomjs failed: null 
[104.131.7.145] stderr: 
[104.131.7.145] Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.[104.131.7.145] 
[104.131.7.145]     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9)
[104.131.7.145]     at _.extend.get (packages/meteor/dynamics_nodejs.js:21)[104.131.7.145] 
[104.131.7.145]     at RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26)
    at ctor (packages/iron:core/lib/iron_core.js:88)
    at Function.Router.createController (packages/iron:router/lib/router.js:188)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39)
    at Object.router (packages/iron:router/lib/router.js:15)
    at next (/opt/frontendsapp/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at Object.Package [as handle] (packages/tap:http-methods/http.methods.server.api.js:367)
[104.131.7.145] spiderable: phantomjs failed: Error: Command failed: [104.131.7.145] 
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5) 
[104.131.7.145] stderr: 
[104.131.7.145] spiderable: phantomjs failed: null 
[104.131.7.145] stderr: 
[104.131.7.145] Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
[104.131.7.145]     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9)[104.131.7.145] 
[104.131.7.145]     at _.extend.get (packages/meteor/dynamics_nodejs.js:21)[104.131.7.145] 
[104.131.7.145]     at RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66)
[104.131.7.145]     at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26)
    at ctor (packages/iron:core/lib/iron_core.js:88)
    at Function.Router.createController (packages/iron:router/lib/router.js:188)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39)
    at Object.router (packages/iron:router/lib/router.js:15)
    at next (/opt/frontendsapp/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at Object.Package [as handle] (packages/tap:http-methods/http.methods.server.api.js:367)
```

looks like I need to update node, going to try and let you guys know

**Comment by thinkxl** [comment]
yes it was that, sorry for opening this issue before trying something else.
