### ISSUE TITLE
Issue after Post is submitted

### ISSUE THREAD

**Issue by nrodastiscornia** [TelescopeJS/Telescope#734]
Hey guys, thanks for your time. Hopefully this is the right place to post this or at least someone can point me in the right direction.

My telescope app is deployed on a EC2 Ubuntu server, via meteor-up. I did the mongo setup using mup too. I created a simple package based on the telescope-blank package, and i added a hook to the **postAfterSubmitMethodCallbacks** array, which calls an external API using the **Meteor's HTTP** library. On my local environment this works without any problems, i put some console.logs to follow the workflow and everything is fine. But when i deploy the callback doesn't seem to be ran. To check this i used **mup's mup logs -f** command and this is what i got 

```javascript
[54.148.142.82] Exception in defer callback: MongoError: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}}[54.148.142.82]
    at Object.Future.wait (/opt/TestApp/app/programs/server/node_modules/fibers/future.js:326:15)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
[54.148.142.82]     at [object Object].MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:634:1)
[54.148.142.82]     at [object Object].mongoConnectionProto.(anonymous function) [as update] (packages/meteorhacks:kadira/lib/hijack/db.js:36:1)
[54.148.142.82]     at Object.fields (packages/matb33:collection-hooks/update.js:75:1)
    at Object.collection.(anonymous function) [as update] (packages/matb33:collection-hooks/collection-hooks.js:99:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:574:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:159:1)
    at addMediaAfterSubmit (packages/telescope-embedly/lib/server/get_embedly_data.js:80:1)
    at app/collections/posts.js:364:18
    - - - - -
    at Object.toError (/opt/TestApp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at /opt/TestApp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/collection/core.js:542:27[54.148.142.82]
    at /opt/TestApp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1129:7
    at /opt/TestApp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1843:9
    at Server.Base._callHandler (/opt/TestApp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /opt/TestApp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at [object Object].MongoReply.parseBody (/opt/TestApp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/opt/TestApp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at [object Object].emit (events.js:95:17)
[54.148.142.82]     at [object Object].<anonymous> (/opt/TestApp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
```

Sadly it doesn't end there... i removed my package, re-deployed the app and this is still happening. Also in both cases with my package and without it the Post still get's saved, but i never see the console logs inside the callback that i added.

Any ideas? Thanks for your time!

**Comment by SachaG** [comment]
Is this the full error? Seems like it might be missing the error message itself?

**Comment by SachaG** [comment]
Also can you link to your GitHub repo?

**Comment by nrodastiscornia** [comment]
Updated!.
Sorry i copied the wrong thing!, i'll upload and let you know

**Comment by nrodastiscornia** [comment]
@SachaG i can't give you access yet because it's on a private repo. I did some more investigation and when i deactivate the embedly package everything works fine, deployed and local... the callback runs.

I'll keep you updated!

**Comment by SachaG** [comment]
Closing this for now, feel free to reopen it if you run into this issue again :)

**Comment by SachaG** [comment]
This should fix it: https://github.com/TelescopeJS/Telescope/commit/0e3a96f50b0660da7360823ad7ac0457cf2c073d
