### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by wanghaisheng** [TelescopeJS/Telescope#800]
macbook 10.10.2
nodejs v0.10.33

when run the 
```
meteor deploy HITProductCatcher
To instantly deploy your app on a free testing server, just enter your email
address!
                                              
Email: edwin_uestc@163.com
                                              
/Users/wanghaisheng/.meteor/packages/meteor-tool/.1.0.40.1h9b355++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:206
						throw(ex);
						      ^
Error: not a tracked temp dir: /Users/wanghaisheng/.meteor/packages/fourseven_scss/.1.0.0.pluzdv++os.osx.x86_64+web.browser+web.cordova
    at Object.Future.wait (/Users/wanghaisheng/.meteor/packages/meteor-tool/.1.0.40.1h9b355++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:326:15)
    at /Users/wanghaisheng/.meteor/packages/meteor-tool/.1.0.40.1h9b355++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:556:31
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/wanghaisheng/.meteor/packages/meteor-tool/.1.0.40.1h9b355++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/wanghaisheng/.meteor/packages/meteor-tool/.1.0.40.1h9b355++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:554:9
    at /Users/wanghaisheng/.meteor/packages/meteor-tool/.1.0.40.1h9b355++os.osx.x86_64+%                                                   
```

**Comment by wanghaisheng** [comment]
meteor update --patch would fix this 
https://github.com/meteor/meteor/issues/3761
