### ISSUE TITLE
Facebook and Twitter login options aren't updated upon settings save

### ISSUE THREAD

**Issue by arnonate** [TelescopeJS/Telescope#828]
Check this out https://www.dropbox.com/s/oewv6zqvjoh233i/screencast%202015-03-18%2021-19-06.mp4?dl=0

I go to check to allow Facebook and Twitter logins and then save the settings. Scrolling back down the checkboxes are empty and if I save they are overwritten.

**Comment by SachaG** [comment]
Oh that's weird. Any errors in the console? Can you link to the live instance and your codebase on GitHub? Thanks for making a screencast btw.

**Comment by arnonate** [comment]
Ya, looks like it's something to do with a function that populates the checkboxes maybe. This is an error I get when I load the settings view.

Exception in template helper: TypeError: undefined is not a function
    at http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:505:283
    at Array.forEach (native)
    at Object.Template.(anonymous function).helpers.hideAuthClass (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:505:257)
    at t (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:60:28387)
    at l._wrapCatchingExceptions (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:60:16297)
    at l.call (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:277:1819)
    at l.mustacheImpl (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:277:1074)
    at Object.l.mustache (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:277:1133)
    at null._render (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:349:2666)
    at a (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:60:18915)
fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:3 Exception in template helper: TypeError: undefined is not a function
    at http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:505:283
    at Array.forEach (native)
    at Object.Template.(anonymous function).helpers.hideAuthClass (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:505:257)
    at t (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:60:28387)
    at l._wrapCatchingExceptions (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:60:16297)
    at l.call (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:277:1819)
    at l.mustacheImpl (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:277:1074)
    at Object.l.mustache (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:277:1133)
    at null._render (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:349:2666)
    at a (http://podcastscope.com/fdac45974fc2a8900f96d5d9f6e0f98be99b3efb.js:60:18915)

**Comment by thangngoc89** [comment]
I ran into this error too. 
Cloned a fresh instance and play around with a few setting. 

console:

```
Exception in template helper: TypeError: undefined is not a function
    at http://localhost:3000/client/views/common/css.js?69b1a290413b276f140e8fd141f6113a71f1a7e3:13:23
    at Array.forEach (native)
    at Object.Template.(anonymous function).helpers.hideAuthClass (http://localhost:3000/client/views/common/css.js?69b1a290413b276f140e8fd141f6113a71f1a7e3:11:15)
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2727:16
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1606:16
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:171:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:108:25)
    at Object.Spacebars.mustache (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:112:39)
    at null._render (http://localhost:3000/client/views/common/template.css.js?8b2c15037b24f29a566fc96352ea18acdb88867a:32:22)
    at doRender (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1866:25)
```

```js
// http://localhost:3000/client/views/common/css.js?69b1a290413b276f140e8fd141f6113a71f1a7e3:13:23
(function(){Template[getTemplate('css')].helpers({
  hideAuthClass: function () {
    
    var authClass = '';
    var authMethods = getSetting('authMethods', ["email"]);
    var selectors = [
      {name: 'email', selector: ".at-pwd-form"},
      {name: 'twitter', selector: "#at-twitter"},
      {name: 'facebook', selector: "#at-facebook"}
    ];
    selectors.forEach(function (method) {
      // if current method is not one of the enabled auth methods, hide it
      if (authMethods.indexOf(method.name) == -1) {
        authClass += method.selector + ", ";
      }
    });

    // unless we're showing at least one of twitter and facebook AND the password form,
    // hide separator
    if (authMethods.indexOf('email') == -1 || (authMethods.indexOf('facebook') == -1 && authMethods.indexOf('twitter') == -1)) {
      authClass += ".at-sep, ";
    }

    return authClass.slice(0, - 2) + "{display:none !important}";

  }
});

})();
```

**Comment by xavcz** [comment]
Hey, @arnonate! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
